---
- name: This updates all the packages avaliable in the system
  hosts: all
  tasks:
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest
  - name: trivially create a file
    shell: echo "Created by ansible tower patching" > /tmp/hello
    args:
      creates: /tmp/This_is_File
